### ISSUE TITLE
HTTPS Error for POST to playlist due to Insufficient client scope

### ISSUE THREAD

**Issue by enthalith** [BoscoDomingo/SpotifyMatcher#5]
HTTP Error for POST to https://api.spotify.com/v1/playlists/330htLm7fwLCb0W4nGmx3v/tracks with Params: {'position': None} returned 403 due to Insufficient client scope

Getting this error where it is unable to post it to the playlist I selected, even when I did not choose a playlist, it would display this error instead "WARNING: There was an error creating the playlist. Please, create one manually and paste its id in the terminal, after your username"

Edit: Additionally, is there a way to make it read japanese and korean characters? Most of my songs are japanese and korean and it breaks the script each time it encounters one.

**Comment by BoscoDomingo** [comment]
Did you set the correct settings for the client app as instructed in the README? Sounds like you simply didn't give the right permissions to write to a playlist

Also, does the playlist already exist? That might explain the "position:None" error

**Comment by enthalith** [comment]
As far as I can follow on the readme, yes. But on the developer page, it shows "No Data Available" which I assume means it was not used, should I paste my ID and secret here + what's in main.py?

Also, yes the playlist already exists. Although, I've tried it without specifying a playlist and it is not creating a new one either, with the above error.

Aside from the above problem, there is also an issue trying to read characters such as オンリー and 어떤 별보다, which makes up of most of my playlist, would like to have some help on this too. Thanks!

Edit: More information. This is the error I got when trying it without having a playlist ID. The developer app and spotify account is the same though.

HTTP Error for GET to https://api.spotify.com/v1/playlists/playlist_id with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Invalid playlist Id

The playlist_id provided did not match any of your existing playlists. Creating a new one...
HTTP Error for POST to https://api.spotify.com/v1/users/username/playlists with Params: {} returned 403 due to You cannot create a playlist for another user.

WARNING:
There was an error creating the playlist. Please, create one manually and paste its id in the terminal, after your username

**Comment by BoscoDomingo** [comment]
So it has to do with the setup, most likely. An error 403 means Spotify is refusing to carry out the actions, potentially due to the kanji you mentioned + wrong setup. I'm not actively maintaining this tool anymore, so I can't really tell you much else besides that.

Give it a try going through the instructions again with a different app and such, and maybe even with a second account, as you can always just make the resulting playlist public and like it from your main account. Also, try removing the songs that may cause issues and find them manually. Best of luck & let me know how it goes!

**Comment by Dinesh686** [comment]
> HTTP Error for POST to https://api.spotify.com/v1/playlists/330htLm7fwLCb0W4nGmx3v/tracks with Params: {'position': None} returned 403 due to Insufficient client scope
> 
> Getting this error where it is unable to post it to the playlist I selected, even when I did not choose a playlist, it would display this error instead "WARNING: There was an error creating the playlist. Please, create one manually and paste its id in the terminal, after your username"
> 
> Edit: Additionally, is there a way to make it read japanese and korean characters? Most of my songs are japanese and korean and it breaks the script each time it encounters one.

Hey, I don't know whether you got it to work. I got it to work a moment ago. 

I put this as the permission for scope: "playlist-modify-public user-library-modify". Entered my playlist_id (easiest way to get this is view the playlist on Spotify Web Player. it is the last characters after the /. If you copy the link from your desktop app some more characters follow with a ?. LIke said in readme you have to exclude ? and the rest if so as in the username for the playlist_id as well) in the terminal after username. Make sure to escape back slashes as mentioned in the readme. I also noticed after music_dir = there was a space unlike in the authorizastion section. For good measure I removed that space as well (but I have no idea whether that had to do something as I'm no programmer. Maybe it was because I didn't escape back slashes because I was confused with the example provided in the image of readme with / within " instead of "" and the disk drive being present in that). After editing all these run the script and the link should fetch the url containing the token with permissions.

It is better to only have songs with English titles or English transliterated titles. I had a Greek band's songs where ones with Greek names weren't matched. The same thing seemed to have happened with ones with Russian titles from a band where ones with English titles had been added. I hope this information was helpful.

**Comment by BoscoDomingo** [comment]
Thank you @Dinesh686, as you mention the instructions in the README should be followed to the T for this to work. Also, cyrillic characters or kanji seem to not play nice with with the TinyTag library, so that's also likely an issue. You could try using a different library that is known to work with those

**Comment by unsync** [comment]
@BoscoDomingo i think the issue was caused by the scope, i'm guessing the playlist was private.

Encountered the same error, made a PR for it, feel free to merge :)

https://github.com/BoscoDomingo/SpotifyMatcher/pull/12

**Comment by BoscoDomingo** [comment]
> @BoscoDomingo i think the issue was caused by the scope, i'm guessing the playlist was private.
> 
> Encountered the same error, made a PR for it, feel free to merge :)
> 
> #12

Tyvm, it's approved and will merge ASAP
